export const GETALLFOODS='GETALLFOODS';
export const GETALLFOODSSUCCESS='GETALLFOODSSUCCESS';
export const GETALLFOODSFAIL='GETALLFOODSFAIL';

export const GETFOOD='GETFOOD';
export const GETFOODSUCCESS='GETFOODSUCCESS';
export const GETFOODFAIL='GETFOODFAIL';

export const ADDCARTLOADING='ADDCARTLOADING';
export const ADDTOCART='ADDTOCART';
export const DELETEFROMCART='DELETEFROMCART';
export const CARTERROR='CARTERROR';
export const FETCHCART='FETCHCART';

export const LOGIN_START='LOGIN_START';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAIL='LOGIN_FAIL';
export const LOGOUT='LOGOUT';

export const ADDORDERSSUCCESS='ADDORDERSSUCCESS';
export const ADDORDERSLOADING='ADDORDERSLOADING';
export const FETCH_ORDERS_SUCCESS='FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL='FETCH_ORDERS_FAIL';
export const FETCHORDERS='FETCHORDERS'